apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: mariadb
type: Opaque
stringData:
  root-password: "ChangeMe@RootPassword123"
  user-password: "ChangeMe@FrappeDB123"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: redis
type: Opaque
stringData:
  password: "ChangeMe@RedisPass123"
---
apiVersion: v1
kind: Secret
metadata:
  name: frappe-secrets
  namespace: frappe
type: Opaque
stringData:
  db-password: "ChangeMe@FrappeDB123"
  redis-password: "ChangeMe@RedisPass123"
  admin-password: "ChangeMe@AdminPass123"
  frappe-site-name: "frappe"
