apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./secrets.encrypted.yaml

patches:
  - path: patch-replicas.yaml

images:
  - name: ghcr.io/etuh/frappe
    newTag: "2026-06-03"
