---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frappe-secrets
  namespace: frappe
spec:
  encryptedData:
    admin-password: AgBkWJHtLlMkxkgyLbauxuLqA/UaddQw0iizSs062pVKQ29ReA7EChQXMqR9nITprXTN9lZmEbWiP7zKBEClJ4z8sHxjpQ7GdVvMCFBbNzKqXY/qnrf7a1h1uR5azcA7wSsMHsVpA+fvvgEFqxYtZs/F44EEoKPs5wDVBAlWfwh8wFof9HCthuRYTnoflVzgNj8Y/qbSyhF+x+uA8yO+Qf2EBSODlzdBsWA+3aIZ0mB9T5g7fKT48J359dk73zIG69xhFPkTyxFkdSaX90DoVLzyaoOqal2ysTWldcX/Yc7XOIXOAmbhnw6RsEZBuFNzgImLNBUGM+mRPDy+m2qi/vXQmJUfAo0uZDk3ZB3C5mTJa36JrnrxofLaB8qlhilVEFTjd3waON+StzlxAlv+j0K/QNWO0lJhNsoXOlZcdGD8EWO/DFkYEsdw2IzURmX5CDzoulLwD8qVRRMZHWgMuqXK/rRwZQxr9Q1WSud8IAwG3FNwxQzpElGkh0TqpWxXrMdt+QAHrTGZCbSAXPycxfL/XW4bNkn2VA7Q9a+u8Ic6RfjZxPiKRbFIDG3ePX6Sw6cSEMgIBc2vhFxuXQs+JQ3Daoq3RybgUrc1idz3DQsghuRRdHM7mL9I0bgnR8o69R6QBG8U0BD/+VZoXxSWHues8BFLKDRCiUQPhvYBYObDeEdrKhpI195wDgdu21jSRaisBHLE3GvNTvr4dsA=
    db-password: AgAHhpsP2d23GTVC8bsEHbkI8vAxvTL3WSDCbeVbu3pICu/xIQfm+FXOnnAXLclrq+/ueSWJrqi2qkqvS/N0P/p5t7IjWBTUnbHtK9TIwgmVshLpPf9PHJn8S3H0Z+RdNEQ/9PyJAql7hB9y8YJjt9vyHjY6TlAwTD1FydApNzRe3V3NGkqwkrWjE8qezrUCX0YJNdZdS5kXdMokoEnvKC4WOdhRW3VOisaRgaUujC4Y5MKvZnOrgQdFrNBkMb+dmdmZeWfWEHkX9oSCsJv66k2T64kz7aOevZtfj4RoMxBwuxl6IKq1vVsSe0afob7ffznb/PQpPaIgUf+CBeAIG9Y/OYrAOEqmcY4QJzDxZP/rQei/FgSyZJuJz2aci13PmT265ZuBWzkhHXDixSRc/2A/TBDGpSdsh+2M+HBKElbXCoxP4N0W2MZ/8Rt4NYEROJuHsPMMiOKaDkq9scmS+bc8tlzI40EAgHwzP3munzAz8RVuXXezc5HPREaLGbaw788ThqJgKvzt+3EgS29maqO+bBMsbH8vtJPjpvIszFBlz2gll0o1nKvU3yLSirXIBXaE77fKRo3JvpCp5SnmC9Z2qrg+T8vGy+LfPpHdoBp2lth4U92oUU6aOjhTzaPmUcjlCWziVbcVRdfalVJJ9SHGV2bh/4XTcVqNAsZiLXXAa9Pzd9AoJ3Zur2SlRX8/sGj0qFUSoFopam9W9w==
  template:
    metadata:
      creationTimestamp: null
      name: frappe-secrets
      namespace: frappe
    type: Opaque
