---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frappe-secrets
  namespace: frappe
spec:
  encryptedData:
    admin-password: AgCx8o3ClHOSM8BfHBl/psd0bYfYKxwd6OB3HiNmXHAFcW1wD4vI6+7QPs4u5YPmSSR0vdLLOMFubdjEQFZlMgkSY/rHT0MjQNeIIgnkil8ZlfhyiLe0e3ZUfiHG17c600n8wgjFWZcyb4vKGi4a8IvvjD48ckwMCRTJd35T0yVv1WUilovMz5G8+lF9zaXQsHma/meqCcof1IxXicvxnXiC7YA36gIKtyynYPsT3sUbWUAVdybU66NUgzSvijQBsT7LeOCuljYiXztyDkf5XsyUkOj58lvVCEM1DoRGivzn7Vw/lj3zwEapH/9B+/MiM1EZ998dDnTP4pgHR1B3RcTbU8PZbflT/SbnoKOTIEAv28PrIJWmaK25G+CDEOzezpbEGD2F14t/JtgzMXq/VwNMSN3AQjoCZwlWfCLdhffCf3WtV0RJI1uP4gqIcUFVlw4FrRRgK4MYzOuMO+y+SoE+xg0TvVH7FJOkgfYEumLd45QcdWvn+Hmw0fweOpBMrZSmzAMAmKVpGFAlvKZ67V7FEOvDC1qLY9migWnHTf2cBoJg/vTb+ze7Z5mF0owgJJBf1bCCSIAtfEdxg/83tZqtSQcTDhTh+2Zq0eTvFmxhXPB74poj69L9HcLP8qLySTXY97HnpwGA9Mjy6ecDJkDIVD8WAU39VLqDqpwVhOhx1bhMirBywLUepZLSzMWXgsu4M/16kFt3sfbybw==
    db-password: AgAp7PbNNVmORe50Srscc5tPiN62bb4ZGBO3rUgAKp838PtRiRBiAfcDWMLCTE+nUJN5mGgBmsO09Rjdv56yznvNfHYvN1msz2ioonQarLwqtE4hI2Gee0qgCEQlXwtJ32p2Ezk31OSZs3xgBWyyG6FJOmvyf6JpKcpMLMD/CIwtWFL28HAneImvEl7osNI3MU54vf2+y5hzgPTydoAzDZe1gVQCb5ykiWeVmsqdZDJ4wVnlXKprqkWGVALmJAaYczCkrnylQSh29a8SZnVeMh96PyQf2/0WwZSFbThx3et0C1TNSE9YNxM/o9EtvrGbf1dOF8Od1Zn690iVFzJW5CsoYw7t4LdibMr9w8IutqTm8TRRWYZAvjGTaeaWmJzibgNMHTNGjAk850nYjsUp7c/AjXYI7giScx/jsFcby5J6twkBayDirKvcFveL6gv7F9YzWhJKBM/HJdR2FQ8E/+sTpBtQ60rUkAP3OL9UBdHR+SBuHfIXw3e1Xy8aQANnn/20TpBtO/RX9DuI/OP8+KEzJrLcfV6FoVwJNLrFiramXcysL17t6zNc0yg9iDVVcYykDQ9VuUvdXZ4KYZgQXxMD8D65AYQBfKkiKBj/joWjI+4V4F8Hcv77hnCrhiAGhz4HAR1l0Lv7irLLf9eWOf1hfvBlUnwvtRIMFtaHdBnmrgDHWzL+Ry8KEHRQG31KaGueUYufJJkuUrm3a8o=
  template:
    metadata:
      creationTimestamp: null
      name: frappe-secrets
      namespace: frappe
    type: Opaque
