---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frappe-secrets
  namespace: frappe
spec:
  encryptedData:
    admin-password: AgCx2lAbQ/0fpHzrrEp2myc1ajTRdF56Mbf7WWbdco9lF9eDFxQ1JHYHpmovylzArYlr/+l9pG7EjMmAsz6gxAxR9NDIq8TB0yOfQ0b3MNPv2TA2yIAgnvaBpLzAgMEtPHm6HUOQs+nNV0IoJnx8C49wQIIaamNKDraaA54uW1KcHB05VtDpGnnSAPyPlvmxreCWCF5jjUTFdrpRXmIKXQt3kRG32Z+f+sKUSMQfjY7SkEZ24b82hGLepJf5ySmC3qjuQ6sNmOZ85zcIewYhIgyWbfi9tQtALpYq1Y2OjX0yRVDwdbTqT4yRuZ2Wp9i3H5IPoWE6ahpokBjjBYUgub1SO8qduEJzqjomcnmY38aCYrJSvt8npRndhPr0b/+rI1+FHZmRlsopuVUPkFxTFcPE3RNaNsnLCUzmGu2Yqw7qUZPAoKuCHDQKb4hSkhepVoK5GznHGTVeRb6z5aEe1YGxzLU6ZRItIYmHKBXfM2hzVhh1EfqJlBXjrsWWOTDLBeX5Ma2tsevNKHVWdkTCtRiA2b8J/KHxS11NzvaNc7ZEpz62hoyqwtTE+3yIAMUtN7LZ1Mj6kHCwXyLzMegSInc+GMdnuoBVTW0RcFkW+46oJfkZq1DUA+4ZuZIWY0OVKPRxWXHbV/z/rz30e3sjlFL9TOiYwj42dY6VZWWe6NCQ9BCs/0RLBmlv+6gSWx+VMRUoWd/SdynAcl5S0Q==
    db-password: AgDCu+lqCoJafTCaFO9a9WCrDbneIir/eFDF74pY6EOQaspbKkAYxNu/gWNLIfn18VwuK/AJY6lY2+zbfiu6WGCF+gv2XJUQjETVlGbhZzzRoxT1AZ3f+wxkIoXHOlJle2hwMwVqMwYRX5Huf0VRny/F3FqC+RkpNv39RHklRoEYtHdfrg6QJr4Ua5WA6bn+LjxFzVyL/mTWnsRiA2eHZwwdpqlfQatuAqkOwxz2WDEfxrZLO8RLjB7cnZH7yPQL2HFmzhOEQ6V/k3giqYWbsqPGYmID8xT6YOD5dVi53rlHgZFOz7FBG+Mghqx/1rAy0shc368Ria1D+MHCg/UujXUDKc8R6CpfSIs5PDGAZ85YIonaeMwUEfPWLLlkqbWfvdEaJ22keIi+aA7xxuwUNG1aGX7Hqd+xxARYHkn71x0uzs59Ep63JrU1NPgesykVLR2IgQia0LWkg6McTg/+4KWKe1wlXeKfJfrX+2i9W40pFVpEI3TUreeed2wrCaBvpjYsiF2tokJio4+WoltRyL9ZcOuFZ0ji3olDJICB0Hj6agQGkwL2beWUolH2BAztjaXxzP+I0fqRD0ADxnPLKh0br4C5Hv6WERohFE/CK6uZ7TCLW19tmUFyu214AEUxTq+jlgzQFbTHJIHsDDVL4b8m9aJ3+TmlZbbDp42eky3UCzkmjdwRZ0q+xZMHGp9IJWIyOC7mcG5PGRFwNyI=
  template:
    metadata:
      creationTimestamp: null
      name: frappe-secrets
      namespace: frappe
    type: Opaque
