---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frappe-secrets
  namespace: default
spec:
  encryptedData:
    admin-password: AgBYXl9iRIj7j5BYlK+ixSbdsaqDtv81Bu45czJfsgj62n+e815pcX+ExtyXxAzGNU4a/nMP4k3VWvLDcnjYqmS08qyDQHXgPhaT8kxHNy+mUWZ1YYTxZTFB6cFc1U1uPPq6/7BoeB93ahHuAevuctS1ez16mQI0Gjqcbg/bC03mL+dKg3QAKs0s/yHs8U8oLe+mXiVh1icrT4tZlAnaPzJRj3ZMsUBxBBuxgY0eXa7FC4iElvV8xisE5j3NVcvfeMPRpOq5S6VoPWJR1LJQssvnrIYoFtU2LqnNYqCUFUXCAM0DUPd9hRmyrpUFbnf0U32BsET9GbcWVWRE+RFtlWwn8vpGx2drWrhVXRRcUaqwCBkYFpenONb3o55b6pFLAy26jwIseiunzCgLCk7IzsKeqcymdzUYt56vaussMd92bbBjM6STv5WOFwoZ2mbk9yJpPxh7BYdzY9VEnzTdOrc0XTMN5uThLHu7uD30/ZqfGNfhkqXRmYZmUIpYZi0Dgd6F6mGJbqF7IGURGZC8LvCIY8ftsX5pK5sRUKQkKkK53Ybw8WLmsvX4Yf8PEZwt5GZFkhk59dPr4w6/XD8jepFunHMUK3oaLj7v5wlx/YlU27KH7jJiqAICOu7icsxmmEKCBa7pwulbCfX8q/ZsMA+qYfEdy60DHOe+8dU84ASpc7iJwo59ZVNnkJU6wWrwteSpR4A+IA==
    db-password: AgAZoNKmNJHwpX0wkHUDA20XhTexVqW0pW9tE+rPgp89cu83O61K8skvARmPjWFYdxs5YZyEXXruYpOSbFdZzxF28HxPnYYMenxQR6okQGDDkgUGp/dM/RtzCETg19AwPXPtY2Cmd/qW1YxZIDIAR8RXfhb/ja39Xn3dTTh1SmSI3j8kXeK7DoBNPiD60BXU8IqPRwpSgS7iY1IoqCdlz2t3iP87ANMqF/tNAWQj1dNsJVKWWaYMDNjw2mnROURnmjm8kxfrHUzY3gz2rNyoknRtewVx49VclCz9LTAbHHV3Wlol6vWpipCYInGy//j0yOYPUmPUbUBkSHq/cgi+m3q3bRyck5i8kmqP2C5sCMYHn38J2OHpvkCPH5Js5aZTvTUMj9Zsy+TDGiH6W/N9tQ+l/BcB96PPb4V3COlIq6J+3QKg7P8vA4CTjCkuZAUbqgv6Zzy27Nc2Lg7jOnVS3UJ2Mh9v53EtVvnkQclVR6Zms+HTalYY2xLLsdnrI9Z5+M2+Zk9+T1IAPkmirwaLQsINsRqeIL9UFxsFUkwKr/NmLITkD5XkYx58Soc3Rau0TI6ZwjW9Ede+GD4EZljH7ZHOzA/HmYW0dT2OKnfJbqpXHMUe/swmVBLKQZFXPXPPPL/tGVbQrwrufNduBA0Fr0EFXx/ZkUahrFxT+zmhfWCXYrM8ymZPWhn2xwOw4Kojs1PghHpkCtKS
  template:
    metadata:
      name: frappe-secrets
      namespace: default
    type: Opaque
