---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frappe-secrets
  namespace: frappe
spec:
  encryptedData:
    admin-password: AgA4e0GBYRrzJHKuPNqQHSHnbvz310t5muvvgPkzXKBzGT1BSLlkI82kcYwJpRKALVBP9ybS08cKjbh85OI1zFZFPEsSk93GuqKc8SG9RERgQ6KH/wkpUIDNkUeOR/INtFkg0qYRk4NIe5sKvh7Q2ECI10Fd2Cfz80pdIcj+QbhTcIB951ZqIhByQb8QowJhAQxWZkBzwWytvUdD86C/frs9o+nQYWpUPknftwQbSS3/7rEuw0+iDmg+bdkZgBuzqgDH9fh6R5TKcNhZioOzn0WpMYmjY7hY5WKR0ddz/4dWI+IiKJxnQmE0mdUclOp7/wljSryDiIoC292lulfCQPH5TDwA/uQtYimcljdiorjUY2EpgqERf0frA+FGaT16B/7/lORynCI1G5LfEYtnI4DvHpMkoBNFUVpNothmqNnocyWgAlHZO15MNsC3TRAxyS0AyKa+hQUB1DGNL59FRQsUi4Vu5ODOMFVmuUVperSqjRvvgX3TuATCrFk708tN85wuUdMcmjyT++AIvugSkzIvnxacfuVLsKgmFVTYeRXuWyt3knNLUR1ls5O9pPGbVhdi2TeIURSNiyYvhLH3FoOkJm7yk6RMGROxbOzYNaQmqCn7AYN+RASLT9J+weABPTJDBo3zuAzX4T/FGxZ4dYNcaNuwR88sB/CZfXOnuj9VrokEocKMy5SilEudDnR7PWL+qd/3AqlbT3G5Zxs=
    db-password: AgC871oy4NVBZBHegvoLM1nuXBqrKwS44YCjhJhOEmMCseQEE5EjN4UbYwKWZY9tYf5UjAZyTZlD1JFgxpn+VXpD/6jnb+6zxNnl0ye/giXq9GaWpsnEz8UVb5F/rh63ijyvYvNpPUezT1jSad9z7Kz+uR1rViaRr2kG8ylGJPkQBtEG8ddtaTUNVk1WIsGPeshK0QPFEEJuhdL91wT5L5FpmkLDe14sawnkAmA1VGSpx4ZNKaGZmP2tshOYko11qu09X/mPX4NteDNQenm+OPsU4Qt06kLXPoWc6qdGG/dyT+gG9485/oiYMSKaQOu3z+C4p+qqHo7LeD59opCzbFhtdcG+lW7snaOT/ztWFgds433Dv/gi6Oi0YYQB0XRRKM5TbllJUBxRj7mHLM3CDpQHrsUSRbs/93fiLAIqsAE9niqe2X7+Q6rGkg09EKyyJBKxMaasUqkgnnDOnA6DaBjnUuxwVNdKgs8rXuWjX7TROMTzMgQcLFVpwZ90aOEKY6moRecPye1Do8Eu/RbQMJohvO9GvQ58ClYb6u7eEJMpWBsFkXrFCkcM6isNA5pouRfdcRL6y25qfv6bki0jCPRPfzJr4bkYuvDKmwSEpvIxsoDDk8ba3FE1UlUJr2yPiwoKyv089Xo2IFZY4K1yl79R6xJlJRIqPBC8NBI4WJlr0UeTm+FX+phK07xX+DH2kpvA4dpI0V2e0DH14w==
  template:
    metadata:
      creationTimestamp: null
      name: frappe-secrets
      namespace: frappe
    type: Opaque
