---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frappe-secrets
  namespace: frappe
spec:
  encryptedData:
    admin-password: AgCfau0o7KoJTnTkzFZ77zlAILEJnLHF3tt2Yg0DqCe4BroZuh9mHQqSHwYSy/I4zSE3hI70LaugcKcIBV8wBs7UBEF/tT+SJGOx5UR9g46nL/a5J6kcvkWB6F66aCQhUw6CgAlJH6QwGm3LAAIxgaE4KEjMX22XnYy/cFFg5ZgdFOl5bIBGc3V1MhUvQdWmeIDZzHoyJqhzyDbST1vH8rE5SEs+tPr31JhWphOGzYj5IT5tt07saf6/xQzPi9XUQziz9H5r3a6+2HsQ4ekovt3vlg6JQ+zceNeRdnOGJNiYL9dus9nxs6yMKLTmhV09tE/c991pAjOoQJ3MV+7F2eEyqxYzk705mqEkENOFwBI4wQj2gLDasCFWIHiIJSJs1KxYdfemlf6h9VsjNwv54pH5yLpimHOcwyV7Ij2VsRV4GIqZrrSI0iyiojbjzI77CFUITYLk7QLSTlqLmnRMW6dzDfbvu3cxgAp+0BgIZNQ4DQBSOg+DmbOtZXHf9EIGrcc7B7mYKFjb2zFEZJ9kqo2Phc3iPx/iDC5p8n3K8ZO2akiM5u3YgrYhYvuprJs65XaHJI35Ba5R1/MoTQPSb1gb8m77zAJ/YYPFyAayrcUXokUQ4Zpo+6bea4zu3MdQ3GIPisSqFlgB8VaYOBBacrugFqSyX5EViY4v4CVjQFbgzwIc6aDu5MwkBrhUfvW7g8CSF0VcIFwMMCvYVg==
    db-password: AgAnG6PIltoo5eBdU4WT3HOmiaKElweriA6eVbzxaIrNqocOYK4RfDk1MQPdQRtUQq/C5N9iYYm2Yuwn/VsIrnV/0Q8+yrcoDfjZlLCyqiLDkvSagos4o2l6I6pGNPVaOF9dHqmdVqdNsN2GZqEgKyWf0moKhlL2JxMGSpjTW8TdgRvskRomKjTpIlR3Jdw2l7f4lZ0ld/mpSExPIu7pGSOD4O3Mikn2XtsYBJNC1L+uv9qOeEqlUdFsvAKOQcoIHDlQmotqxm3cLaDEQvtjodsKpdKt4hirlhKkjaDQRUErkiexZs6aX3kAtOa/wrYJx2L7K/U1rOt39P6awqYc5otqaDBKPdDbTbYl+Y6RZEF65BIxlG1HYzTX8TwccAr/c+oaLfsyDMW37q5M/FgqtXZ3GmXfJEVohit9fPemVE/1DcBkIq5E4cqTg0XnSMHQPOO/n2JphhY95U1og3niqggX3fzRXjsi5m/Rv3RoGFVa1Ky2TPgGyREZRghPtTXwQZgWhdgldp9VK8O0n/9FXhgmImvst+JJRCbn3Ix3jW1jzF2cTN/79NKrey/CTRbuwVg4I25WSy15/DxloleIUjs4BBzpikY9HFPgFRnm/LA0KCV7W+cbcwh63mEBJjvfenzlH85r7d8xHuXiYBFWJnIRDBWgtf1zeOuOcrRx2ojD6O5hR6wRH1n+BvEuQw21hrVs7xzzq9Da58R7
  template:
    metadata:
      creationTimestamp: null
      name: frappe-secrets
      namespace: frappe
    type: Opaque
