apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include mime.types;
      upstream backend {
          server backend:8000;
      }
      upstream websocket {
          server websocket:9000;
      }
      server {
          listen 8080;
          location / {
              proxy_pass http://backend;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
          location /socket.io/ {
              proxy_pass http://websocket;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
          }
          location /assets/ {
              alias /home/frappe/frappe-bench/sites/assets/;
            expires 1y;
            add_header Cache-Control "public, immutable";
          }
      }
    }
