apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
        - name: config
          configMap:
            name: nginx-config
