apiVersion: batch/v1
kind: CronJob
metadata:
  name: frappe-backup
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: ghcr.io/etuh/frappe:2026-05-08
              command: ["/home/frappe/frappe-bench/env/bin/bench"]
              args: ["--site", "$(SITE_NAME)", "backup", "--with-files"]
              env:
                - name: SITE_NAME
                  value: "frappe.dairyndumberi.local"
              volumeMounts:
                - name: sites
                  mountPath: /home/frappe/frappe-bench/sites
                - name: site-config
                  mountPath: /home/frappe/frappe-bench/sites/common_site_config.json
                  subPath: common_site_config.json
          volumes:
            - name: sites
              persistentVolumeClaim:
                claimName: frappe-sites
            - name: site-config
              configMap:
                name: common-site-config
