apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-sites
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: rwx-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
