apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-sites
spec:
  storageClassName: rwx-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
