apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-long
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe
      role: worker-long
  template:
    metadata:
      labels:
        app: frappe
        role: worker-long
    spec:
      containers:
        - name: worker
          image: ghcr.io/etuh/frappe:2026-05-08
          command: ["bench"]
          args: ["--site", "$(SITE_NAME)", "worker", "--queue", "long"]
          env:
            - name: SITE_NAME
              value: "frappe.dairyndumberi.local"
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
            - name: site-config
              mountPath: /home/frappe/frappe-bench/sites/common_site_config.json
              subPath: common_site_config.json
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
        - name: site-config
          configMap:
            name: common-site-config
