apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-short
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe
      role: worker-short
  template:
    metadata:
      labels:
        app: frappe
        role: worker-short
    spec:
      containers:
        - name: worker
          image: custom-frappe:v16.17.0
          command: ["/home/frappe/frappe-bench/env/bin/bench"]
          args: ["--site", "$(SITE_NAME)", "worker", "--queue", "short"]
          env:
            - name: SITE_NAME
              value: "frappe.dairyndumberi.local"
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
